export const ADMIN_TEXTS = {
  bookingList: {
    status: {
      PENDING_DEPOSIT: "Chờ cọc",
      CONFIRMED: "Đã xác nhận",
      COMPLETED: "Hoàn thành",
      CANCELLED: "Đã hủy",
      NO_SHOW: "Vắng mặt"
    },
    errorFetch: "Không thể tải danh sách đặt bàn.",
    errorUpdate: "Đã có lỗi xảy ra.",
    updateSuccess: "Cập nhật trạng thái thành công.",
    updateFail: "Cập nhật thất bại.",
    title: "Danh sách đặt bàn (Hàng ngày)",
    subtitle: "Quản lý và theo dõi khách hàng đến quán.",
    searchPlaceholder: "Tìm tên khách hoặc số điện thoại...",
    filterAllStatus: "Tất cả trạng thái",
    thTime: "Thời gian",
    thCustomer: "Khách hàng",
    thTableGuest: "Bàn & Khách",
    thNote: "Ghi chú",
    thStatus: "Trạng thái",
    loading: "Đang tải dữ liệu...",
    emptyList: "Không có đơn đặt bàn nào",
    emptyListHint: "Thử thay đổi ngày hoặc bộ lọc trạng thái",
    guestWalkIn: "Khách Vãng Lai",
    phoneNa: "Không có SĐT",
    guestUnit: "khách",
    tableUnassigned: "Chưa xếp bàn",
    noNote: "Không có"
  },
  branchManagement: {
    title: "Quản lý Chi nhánh",
    subtitle: "Quản lý tất cả thông tin và trạng thái hoạt động của chi nhánh.",
    addBranchBtn: "Thêm chi nhánh mới"
  },
  branchList: {
    errorUpdateStatus: "Không thể cập nhật trạng thái chi nhánh. Vui lòng thử lại.",
    statusOpen: "MỞ CỬA",
    statusFull: "HẾT BÀN",
    statusClosed: "ĐÓNG CỬA",
    statusSetup: "SETUP",
    searchPlaceholder: "Tìm theo Mã, Tên, Địa chỉ, Quản lý...",
    filterAllStatus: "Tất cả trạng thái",
    thCode: "MÃ CHI NHÁNH",
    thImage: "HÌNH ẢNH",
    thInfo: "THÔNG TIN",
    thContact: "LIÊN HỆ",
    thStatus: "TRẠNG THÁI",
    thActions: "HÀNH ĐỘNG",
    loading: "Đang tải dữ liệu...",
    unassigned: "Chưa chỉ định",
    noHotline: "Không có",
    btnToggleStatus: "Nhấn để chuyển đổi trạng thái",
    btnView: "Xem chi tiết",
    btnEdit: "Chỉnh sửa",
    btnDelete: "Xóa / Vô hiệu hóa",
    emptyList: "Không tìm thấy chi nhánh nào phù hợp.",
    paginationShowing: "Hiển thị",
    paginationTo: "đến",
    paginationOf: "trong số",
    paginationBranches: "chi nhánh"
  },
  addBranch: {
    errorNameAddress: "Name and Full Address are required!",
    errorManager: "Please assign a Manager for this branch!",
    errorSave: "Failed to create branch. Please try again.",
    successSave: "Branch details saved! Please upload branch photos.",
    breadcrumbList: "Quản lý Chi nhánh",
    breadcrumbAdd: "Thêm chi nhánh mới",
    title: "Thêm Chi nhánh mới",
    btnBack: "Quay lại",
    btnCancel: "Hủy",
    btnContinueToOps: "Tiếp tục thiết lập",
    btnSaveContinue: "Lưu & Tiếp tục"
  },
  addBranchForm: {
    loadingMap: "Đang tải bản đồ...",
    titleProfile: "Hồ sơ chi nhánh",
    subtitleProfile: "Thông tin cơ bản của chi nhánh bạn quản lý",
    labelName: "Tên chi nhánh",
    labelHotline: "Hotline",
    unassignedHotline: "Chưa cập nhật",
    labelAddress: "Địa chỉ",
    labelManager: "Quản lý trực tiếp",
    unassignedManager: "Chưa phân công",
    labelAmenities: "Tiện ích chi nhánh",
    noAmenitiesProfile: "Không có tiện ích nào",
    titleForm: "Thông tin chi nhánh",
    inputNameLabel: "Tên chi nhánh",
    inputNamePlaceholder: "VD: SpotOn Quận 1 - Bến Nghé",
    inputDescLabel: "Mô tả chi nhánh",
    inputDescPlaceholder: "Giới thiệu ngắn về không gian, phong cách phục vụ của chi nhánh...",
    inputCityLabel: "Tỉnh/Thành phố",
    inputDistrictLabel: "Quận/Huyện",
    inputDistrictPlaceholder: "Chọn Quận/Huyện",
    inputWardLabel: "Phường/Xã",
    inputWardPlaceholder: "VD: Phường Xuân Khánh",
    inputStreetLabel: "Tên đường, Số nhà",
    inputStreetPlaceholder: "VD: 3/2",
    inputFullAddressLabel: "Địa chỉ đầy đủ",
    inputFullAddressPlaceholder: "VD: Khu II, Đ. 3/2, Phường Xuân Khánh, Ninh Kiều, Cần Thơ",
    inputMapLabel: "Vị trí trên bản đồ",
    inputHotlineLabel: "Hotline chi nhánh",
    inputHotlinePlaceholder: "VD: 028 1234 5678",
    inputHotlineHint: "Số điện thoại này sẽ hiển thị cho khách hàng đặt bàn.",
    inputManagerLabel: "Phân công Quản lý",
    inputManagerPlaceholder: "Chọn một quản lý...",
    inputManagerEmpty: "Không tìm thấy quản lý trong hệ thống",
    inputManagerHint: "Chỉ những tài khoản có quyền Quản lý (Manager) mới hiển thị ở đây.",
    inputAmenitiesLabel: "Tiện ích chi nhánh",
    noAmenitiesSystem: "Không có tiện ích nào trong hệ thống."
  },
  editBranch: {
    errorFetch: "Failed to load branch data.",
    errorValidation: "Tên chi nhánh, Quận/Huyện và Địa chỉ đầy đủ là bắt buộc!",
    errorManager: "Please assign a Manager for this branch!",
    errorUpdate: "Lỗi khi cập nhật chi nhánh. Vui lòng thử lại.",
    successUpdate: "Đã cập nhật chi nhánh",
    breadcrumbList: "Branch Management",
    breadcrumbEdit: "Edit Branch",
    titleManager: "Chi nhánh:",
    titleAdmin: "Edit Branch:",
    loadingName: "Loading...",
    subtitle: "Quản lý thông tin và các giới hạn vận hành của chi nhánh.",
    btnEditMap: "Chỉnh Sửa Sơ Đồ Bàn",
    btnCancel: "Hủy",
    btnSave: "Lưu thay đổi",
    btnSaving: "Đang lưu...",
    warningTitle: "Cảnh báo đóng chi nhánh!",
    warningDesc1: "Hiện tại chi nhánh đang có",
    warningDesc2: "đơn đặt bàn chưa được xử lý. Bạn có chắc chắn muốn đóng cửa chi nhánh không? Khách hàng sẽ bị ảnh hưởng.",
    warningBtnCancel: "Hủy bỏ",
    warningBtnClose: "Đóng chi nhánh"
  },
  addBranchOps: {
    titleRules: "Quy định hoạt động",
    titleOpsRules: "Operational Rules",
    titleServicePeriods: "Service Periods (Ca phục vụ)",
    descServicePeriods: "Thời gian mở cửa và nhận khách cho từng ca. Các mốc thời gian này được tải mặc định từ hệ thống.",
    lunch: "Ca Trưa (Lunch)",
    dinner: "Ca Tối (Dinner)",
    timeOpen: "Giờ mở cửa",
    timeClose: "Đóng cửa",
    timeLastBooking: "Nhận khách cuối",
    timeLastOrder: "Order cuối",
    titleLimits: "Giới hạn vận hành (Operation Limits)",
    descLimits: "Thiết lập các ngưỡng giới hạn để hệ thống tự động chống quá tải (Overbooking).",
    thresholdLabel: "Ngưỡng quá tải chung (%)",
    thresholdHint: 'Hệ thống sẽ báo "Hết bàn" khi sức chứa đạt ngưỡng này.',
    titleStatus: "Trạng thái phục vụ ban đầu",
    descStatus: "Thiết lập trạng thái hiển thị của chi nhánh với khách hàng.",
    statusClosed: "Đóng cửa / Sắp khai trương",
    statusOpen: "Đang mở / Nhận đặt bàn"
  },
  categories: {
    title: "Quản lý Danh mục",
    description: "Thêm, sửa, xóa các danh mục thực đơn của hệ thống.",
    addCategory: "Thêm danh mục mới",
    editCategory: "Sửa",
    deleteCategory: "Xóa",
    categoryName: "TÊN DANH MỤC",
    categoryNamePlaceholder: "VD: Khai vị",
    itemCount: "SỐ MÓN",
    actions: "THAO TÁC",
    confirmDelete: "Xác nhận xóa?",
    btnYes: "Có",
    btnNo: "Hủy",
    errorNotEmpty: "Không thể xóa danh mục đang có món ăn!",
    empty: "Chưa có danh mục nào."
  },
  liveMap: {
    title: "Live Map:",
    statusTempClosed: "Tạm đóng",
    subtitle: "Update physical table status in real-time",
    branchStatusLabel: "Hoạt động quán:",
    branchStatusClosed: "ĐANG ĐÓNG",
    branchStatusOpen: "ĐANG MỞ",
    btnRefresh: "Refresh",
    zoneStatusClosed: "Đóng",
    zoneStatusLabel: "Trạng thái khu vực:",
    tableModalTitle: "Bàn số",
    tableModalSubtitle: "Cập nhật trạng thái"
  },
  mapEditor: {
    errorLoad: "Không thể tải dữ liệu sơ đồ bàn.",
    successCreateZone: "Thêm khu vực",
    successUpdateZone: "Cập nhật khu vực thành công!",
    successDeleteZone: "Xóa khu vực",
    successCreateTable: "Thêm bàn",
    successUpdateTable: "Cập nhật bàn thành công!",
    successDeleteTable: "Xóa bàn",
    successSaveLayout: "Lưu sơ đồ bàn thành công!",
    errorSelectZoneFirst: "Vui lòng chọn một khu vực trước khi nhập từ mẫu.",
    errorLoadTemplates: "Không thể tải danh sách mẫu.",
    successApplyTemplate: "Đã áp dụng sơ đồ mẫu thành công!",
    errorApplyTemplate: "Lỗi khi áp dụng sơ đồ mẫu.",
    title: "Sơ Đồ Bàn",
    loading: "Đang tải...",
    btnHideSidebar: "Ẩn cột khu vực",
    btnShowSidebar: "Hiện cột khu vực",
    btnImportTemplate: "Nhập từ Mẫu",
    btnRefresh: "Làm mới",
    deleteZoneTitle: "Xóa khu vực?",
    deleteTableTitle: "Xóa bàn?",
    deleteZoneDesc: "Tất cả bàn trong khu vực này cũng sẽ bị xóa. Hành động này không thể hoàn tác.",
    deleteTableDesc: "Bàn sẽ bị xóa khỏi khu vực. Hành động này không thể hoàn tác.",
    importModalTitle: "Nhập từ Sơ đồ mẫu",
    importModalWarning: "Lưu ý: Bàn trong khu vực đang chọn sẽ bị ghi đè hoàn toàn.",
    importModalEmpty: "Chưa có Sơ đồ mẫu nào trong hệ thống.",
    importModalBtnSelect: "Chọn",
    importModalBtnCancel: "Hủy",
    confirmImportTitle: "Xác nhận ghi đè?",
    confirmImportDesc1: "Hành động này sẽ xóa",
    confirmImportDesc2: "toàn bộ",
    confirmImportDesc3: "bàn hiện tại trong khu vực",
    confirmImportDesc4: "và thay thế bằng sơ đồ mẫu. Bạn có chắc chắn không?",
    confirmImportBtnCancel: "Hủy",
    confirmImportBtnConfirm: "Xác nhận",
    sidebarOverviewTitle: "Tổng Quan",
    sidebarOverviewSubtitle: "Sơ đồ bàn chi nhánh",
    sidebarStatZones: "Khu vực",
    sidebarStatTables: "Tổng bàn",
    sidebarStatEmpty: "Còn trống",
    sidebarListTitle: "Danh sách khu vực",
    sidebarBtnAdd: "Thêm",
    sidebarLoading: "Đang tải...",
    sidebarEmptyList: "Chưa có khu vực nào",
    sidebarEmptyHint: "Nhấn \"Thêm\" để tạo khu vực đầu tiên",
    sidebarCollapseArea: "Thu gọn khu vực",
    sidebarExpandArea: "Mở rộng khu vực",
    sidebarTableUnit: "bàn",
    sidebarSeatUnit: "chỗ",
    sidebarEditArea: "Sửa khu vực",
    sidebarDeleteArea: "Xóa khu vực",
    sidebarNoTable: "Chưa có bàn nào",
    tplLabel2Person: "Bàn 2 người",
    tplLabel4Person: "Bàn 4 người",
    tplLabel8Person: "Bàn 8 người (CN)",
    tplLabel8PersonCircle: "Bàn 8 người (Tròn)",
    tplErrorInvalidImage: "Vui lòng chọn file hình ảnh hợp lệ.",
    tplErrorUpload: "Upload lỗi: ",
    tplErrorUpdate: "Lỗi khi cập nhật ảnh mẫu bàn.",
    tplTitle: "CHỌN THEO SỐ LƯỢNG KHÁCH",
    tplDragHint: "Kéo và thả vào mặt bằng",
    tplChangeImgHint: "Đổi ảnh mẫu bàn này",
    tplPersonUnit: "NGƯỜI",
    tplSizePrefix: "Kích thước: ",
    modalZoneTitleCreate: "Thêm Khu Vực Mới",
    modalZoneTitleEdit: "Chỉnh Sửa Khu Vực",
    modalZoneSubtitleCreate: "Tạo một khu vực mới trong chi nhánh",
    modalZoneSubtitleEdit: "Cập nhật thông tin khu vực",
    modalZoneName: "Tên khu vực",
    modalZoneNamePlaceholder: 'VD: "Tầng 1", "Sân vườn", "VIP"',
    modalZoneCapacity: "Sức chứa tối đa (người)",
    modalZoneCapacityPlaceholder: "VD: 50",
    modalZoneCapacityHint: "Để 0 nếu không giới hạn",
    modalZoneBtnCancel: "Hủy",
    modalZoneBtnSaving: "Đang lưu...",
    modalZoneBtnCreate: "Thêm Khu Vực",
    modalZoneBtnSave: "Lưu Thay Đổi",
    modalTableTitleCreate: "Thêm Bàn Mới",
    modalTableTitleEdit: "Chỉnh Sửa Bàn",
    modalTableZoneLabel: "Khu vực: ",
    modalTableNumber: "Số bàn",
    modalTableNumberPlaceholder: 'VD: "A1"',
    modalTableCapacity: "Sức chứa",
    modalTableWidth: "Chiều rộng (px)",
    modalTableHeight: "Chiều dài (px)",
    modalTableHeightHint: "Bàn tròn sẽ dùng chung một đường kính",
    modalTableImage: "Hình ảnh bàn (Tùy chọn)",
    modalTableBtnDeleteImg: "Xóa ảnh",
    modalTableBtnChangeImg: "Đổi ảnh",
    modalTableBtnUploadImg: "Chọn ảnh",
    modalTableImgHint: "Tải ảnh bàn thực tế (Tối đa 5MB)",
    modalTableStatusLabel: "Trạng thái",
    modalTableBtnDelete: "Xóa bàn",
    modalTableBtnDeleteDisabledHint: "Không thể xóa bàn đang có khách hoặc đã đặt",
    modalTableBtnCancel: "Hủy",
    modalTableBtnCreate: "Thêm Bàn",
    modalTableBtnSave: "Lưu",
    modalTableBtnSaving: "Đang lưu...",
    modalTableBtnUploading: "Đang tải...",
    modalTableErrorInvalidImage: "Vui lòng chọn file hình ảnh hợp lệ.",
    modalTableErrorImageSize: "Kích thước ảnh tối đa là 5MB.",
    modalTableErrorUploadFail: "Lỗi khi tải ảnh lên.",
    modalTableErrorUploadError: "Đã xảy ra lỗi khi tải ảnh lên.",
    canvasSelectAreaTitle: "Chọn khu vực",
    canvasSelectAreaHint: "Vui lòng chọn hoặc tạo một khu vực để bắt đầu sắp xếp bàn",
    canvasDropTemplateError: "Lỗi khi drop template:",
    canvasUnitTable: "bàn",
    canvasUnitCapacity: "Sức chứa: ",
    canvasUnitPerson: " người",
    canvasBtnUndo: "Hủy thay đổi",
    canvasBtnSave: "Lưu Sơ Đồ",
    canvasBtnSaving: "Đang lưu...",
    canvasEmptyTitle: "Chưa có bàn nào",
    canvasEmptyHint: "Nhấn \"Thêm bàn\" để bắt đầu",
    canvasTableTitlePrefix: "Bàn ",
    canvasSeatSuffix: " chỗ",
    canvasEditTable: "Sửa bàn ",
    canvasResizeTable: "Kéo để thay đổi kích thước bàn ",
    deleteModalBtnCancel: "Hủy",
    deleteModalBtnDeleting: "Đang xóa...",
    deleteModalBtnConfirm: "Xác nhận xóa"
  },
  mapTemplates: {
    loadError: "Không thể tải danh sách mẫu sơ đồ.",
    createModalTitle: "Tạo Sơ đồ Mới",
    createModalNameLabel: "Tên sơ đồ mẫu",
    createModalNamePlaceholder: "Ví dụ: Tầng 1, Khu vực VIP...",
    createModalDescLabel: "Mô tả (không bắt buộc)",
    createModalDescPlaceholder: "Nhập mô tả cho sơ đồ mẫu này...",
    createModalBtnCancel: "Hủy",
    createModalBtnSubmit: "Tạo sơ đồ",
    createSuccess: "Tạo mẫu thành công",
    createError: "Không thể tạo sơ đồ mới.",
    createException: "Lỗi khi tạo mẫu",
    deleteSuccess: "Xóa mẫu thành công",
    deleteException: "Lỗi khi xóa mẫu",
    pageTitle: "Quản lý Sơ đồ mẫu",
    pageSubtitle: "Tạo và chỉnh sửa các sơ đồ để các chi nhánh sử dụng.",
    btnAddTemplate: "Thêm sơ đồ mới",
    emptyListTitle: "Chưa có sơ đồ mẫu nào được tạo.",
    btnCreateFirstTemplate: "Tạo Mẫu Đầu Tiên",
    tableColName: "TÊN SƠ ĐỒ",
    tableColDesc: "MÔ TẢ",
    tableColDate: "NGÀY TẠO",
    tableColActions: "THAO TÁC",
    noDescription: "Không có mô tả",
    btnEditDesign: "Sửa thiết kế",
    deleteModalTitle: "Xóa Sơ đồ Mẫu",
    deleteModalWarningPrefix: "Bạn có chắc chắn muốn xóa sơ đồ mẫu ",
    deleteModalWarningSuffix: " không? Hành động này không thể hoàn tác.",
    deleteModalBtnCancel: "Hủy",
    deleteModalBtnDelete: "Xóa sơ đồ",
    newTemplatePrefix: "Sơ đồ mới ",
    defaultDescription: "Mô tả mẫu",
    editorLoadError: "Không thể tải dữ liệu sơ đồ mẫu.",
    editorTableAddSuccess: "Thêm bàn ",
    editorTableAddSuccessSuffix: " thành công!",
    editorTableUpdateSuccess: "Cập nhật bàn thành công!",
    editorTableDeleteSuccess: "Xóa bàn ",
    editorTableDeleteSuccessSuffix: " thành công!",
    editorLayoutSaveSuccess: "Lưu sơ đồ bàn thành công!",
    editorBreadcrumbParent: "Map Templates",
    editorBreadcrumbChild: "Template Editor",
    editorTitle: "Sơ Đồ Mẫu",
    editorLoading: "Đang tải...",
    editorBtnRefresh: "Làm mới",
    editorDeleteZoneTitle: "Xóa khu vực?",
    editorDeleteTableTitle: "Xóa bàn?",
    editorDeleteZoneDesc: "Tất cả bàn trong khu vực này cũng sẽ bị xóa. Hành động này không thể hoàn tác.",
    editorDeleteTableDesc: "Bàn sẽ bị xóa khỏi khu vực. Hành động này không thể hoàn tác."
  },
  menu: {
    tabAll: "Tất cả món",
    deleteError: "Lỗi khi xóa món ăn.",
    pageTitle: "Quản lý Thực đơn",
    pageSubtitle: "Quản lý các món ăn, giá bán và giới hạn giá cho từng chi nhánh.",
    btnAddItem: "Thêm món mới",
    addUploadError: "Upload ảnh thất bại.",
    addCreateError: "Lỗi khi tạo món ăn. Vui lòng thử lại.",
    addBreadcrumbParent: "Quản lý Thực đơn",
    addBreadcrumbChild: "Thêm món mới",
    addStep3Title: "Bước 3: Hình ảnh & Xem lại",
    addStep3Desc: "Hoàn thiện hình ảnh và kiểm tra cấu hình trước khi xuất bản.",
    addTitle: "Thêm món mới",
    addDesc: "Tạo món ăn hoặc sản phẩm mới cho thực đơn của bạn.",
    addBtnDraft: "Lưu nháp",
    addStep1: "Basic Details",
    addStep2: "Pricing & Branches",
    addStep3: "Media & Review",
    addFinalSummary: "Final Summary",
    addCategory: "Category",
    addBasePrice: "Base Price",
    addActiveBranches: "Active Branches",
    addProTips: "Pro Tips",
    addTipPhotoTitle: "Photography Quality",
    addTipPhotoDesc: "Items with high-resolution, bright photos see 3x higher click-through rates. Avoid using stock images when possible.",
    addTipDietTitle: "Dietary Search",
    addTipDietDesc: "Dietary tags are the most used filter in the consumer app. Ensure \"Spicy\" or \"Gluten-Free\" is accurately marked for better visibility.",
    addTipOptimize: "Optimize for more sales",
    addTipNameTitle: "Naming",
    addTipNameDesc: "Use descriptive adjectives in titles. \"Signature Beef Pho\" sells 22% better than just \"Pho\".",
    addTipPriceTitle: "Dynamic Pricing",
    addTipPriceDesc: "Consider setting a slightly higher base price for 'Premium Location' branches...",
    addBtnBack: "Back",
    addBtnBackStep: "Back to Step ",
    addBtnPublishing: "Publishing...",
    addBtnPublish: "Publish Item",
    addBtnNext: "Next",
    editNotFoundLog: "Item not found for menuId:",
    editUploadError: "Upload ảnh thất bại.",
    editUpdateError: "Lỗi khi cập nhật món ăn. Vui lòng thử lại.",
    editLoadingItem: "Đang tải thông tin món ăn...",
    editBreadcrumbParent: "Menu Management",
    editBreadcrumbChild: "Edit Item",
    editStep3Title: "Step 3: Media & Review",
    editStep3Desc: "Update the image and finalize configurations before saving.",
    editTitle: "Edit Menu Item",
    editDescPrefix: "Chỉnh sửa thông tin cho \"",
    editDescSuffix: "\".",
    editBtnSaveDraft: "Save Draft",
    editItemSummary: "Item Summary",
    editCategory: "Danh mục",
    editBasePrice: "Base Price",
    editBranches: "Chi nhánh",
    editTipPhotoTitle: "Lưu ý khi sửa ảnh",
    editTipPhotoDesc: "Nếu bạn không chọn ảnh mới, ảnh cũ sẽ được giữ nguyên. Chọn ảnh mới để thay thế toàn bộ ảnh hiện tại.",
    editTipStep1Desc1: "Cập nhật tên món ăn sẽ được đồng bộ ngay ra trang menu công khai sau khi lưu.",
    editTipStep1Desc2: "Thay đổi danh mục sẽ di chuyển món ăn sang nhóm danh mục mới.",
    editTipStep2Desc1: "Thay đổi giá sẽ áp dụng ngay lập tức tại tất cả các chi nhánh đã chọn.",
    editTipStep2Desc2: "Hệ thống sẽ cảnh báo nếu có chi nhánh đang bán ngoài khoảng giá mới.",
    editBtnSaving: "Đang lưu...",
    editBtnSave: "Lưu Thay Đổi",
    editBtnNext: "Next",
    tableColItem: "MÓN ĂN",
    tableColCategory: "DANH MỤC",
    tableColBasePrice: "GIÁ CƠ BẢN (VNĐ)",
    tableColPriceRange: "KHOẢNG GIÁ (MIN-MAX)",
    tableColStatus: "TRẠNG THÁI",
    tableColActions: "THAO TÁC",
    tableEmpty: "Không có món ăn nào trong danh mục này.",
    tableFlexiblePrice: "Flexible (No Limits)",
    tableConfirmDelete: "Xóa?",
    tableBtnYes: "Có",
    tableBtnCancel: "Hủy",
    tableBtnEdit: "Sửa món",
    tableBtnDelete: "Xóa món",
    tablePaginationEmpty: "No items found",
    tablePaginationPrefix: "Showing ",
    tablePaginationTo: " to ",
    tablePaginationOf: " of ",
    tablePaginationSuffix: " items",
    basicsFetchError: "Failed to fetch categories",
    basicsTitle: "Basic Information",
    basicsDesc: "Provide the primary details for this item that customers will see.",
    basicsItemName: "Item Name",
    basicsCategory: "Primary Category",
    basicsCategorySelect: "-- Chọn danh mục --",
    basicsDescription: "Description",
    basicsDietaryTitle: "Dietary & Attributes",
    basicsDietaryTags: "Dietary Tags",
    basicsTagVegetarian: "Vegetarian",
    basicsTagVegan: "Vegan",
    basicsTagSpicy: "Spicy Option",
    basicsTagGluten: "Gluten Free",
    mediaUploadErrorType: "Vui lòng chọn file ảnh (JPEG, PNG, WebP).",
    mediaUploadErrorSize: "File ảnh quá lớn. Tối đa 5MB.",
    mediaUploadTitle: "Media Upload",
    mediaPrimaryImage: "Primary Item Image",
    mediaBtnChangeImage: "Đổi ảnh",
    mediaBtnRemoveImage: "Xóa ảnh",
    mediaUploadStatus: "Uploaded",
    mediaClickToUpload: "Click to upload",
    mediaFormatInfo: "JPEG, PNG, WebP • Max 5MB",
    mediaGalleryTitle: "Lifestyle & Preparation Gallery",
    mediaGalleryInfo: "Add up to 5 additional photos showing the preparation process or the dish in a lifestyle setting to increase conversion by 24%.",
    mediaDietaryTitle: "Dietary & Attributes",
    mediaBtnAddTag: "Add Tag",
    mediaReviewTitle: "Review & Visibility",
    mediaReviewDesc: "If enabled, branch managers cannot delete this item from their local menus. This ensures consistent brand offerings across all locations.",
    mediaCoreItem: "CORE\nITEM",
    pricingFetchError: "Failed to fetch branches:",
    pricingErrMinMax: "Min Price must be less than or equal to Max Price.",
    pricingErrBaseMin: "Base Price must be >= Min Price.",
    pricingErrMinBase: "Min Price must be <= Base Price.",
    pricingErrBaseMax: "Base Price must be <= Max Price.",
    pricingErrMaxBase: "Max Price must be >= Base Price.",
    pricingTitle: "Pricing & Branch Override Rules",
    pricingDesc: "Set the global base price and define the min/max range that branch managers can adjust within.",
    pricingBr01Title: "Price Range Violation (BR-01)",
    pricingBr01Desc: "Base Price must be between Min and Max Price (Min ≤ Base ≤ Max).",
    pricingMinPrice: "Min Price",
    pricingBasePrice: "Base Price",
    pricingGlobalDefault: "Global default",
    pricingMaxPrice: "Max Price",
    pricingOverrideRange: "Branch Override Range",
    pricingWithinRangeInfo: "is within the allowed range.",
    pricingAdjustInfo: "Branch managers can adjust their local price within [Min–Max]. Base Price is the system default applied globally.",
    pricingBranchDist: "Branch Distribution",
    pricingBtnSelectAll: "Select All",
    pricingSelectInfo: "Select locations to feature this item.",
    pricingNoBranches: "No branches found.",
    pricingGlobalAvailTitle: "Global Availability",
    pricingGlobalAvailDesc: "Set initial status across all selected branches upon creation.",
    pricingBtnActive: "Active",
    pricingBtnDraft: "Draft",
    modalUpdateSuccess: "Cập nhật món ăn thành công!",
    modalUpdateError: "Lỗi khi cập nhật món ăn.",
    modalTitle: "Sửa Món Ăn",
    modalItemName: "Tên món",
    modalDesc: "Mô tả",
    modalBasePrice: "Giá cơ bản",
    modalMinPrice: "Giá tối thiểu",
    modalMaxPrice: "Giá tối đa",
    modalBtnCancel: "Hủy",
    modalBtnSaving: "Đang lưu...",
    modalBtnSave: "Lưu Thay Đổi"
  },
  settings: {
    errLoadRules: "Không thể tải chính sách đặt bàn.",
    errDepositRange: "Tỷ lệ cọc phải từ 0-100%.",
    errInvalidValues: "Vui lòng nhập các giá trị hợp lệ lớn hơn 0.",
    successSaveRules: "Lưu chính sách đặt bàn thành công!",
    errSaveRules: "Lưu thất bại. Vui lòng thử lại.",
    loadingConfig: "Đang tải cấu hình...",
    title: "Cài đặt Hệ thống",
    subtitle: "Quản lý cấu hình chung cho toàn bộ nền tảng SpotOn.",
    globalPolicyTitle: "Chính sách Đặt bàn Toàn cầu",
    globalPolicyDesc: "Những quy định này áp dụng cho tất cả chi nhánh theo mặc định.",
    lblDeposit: "Tỷ lệ cọc",
    descDeposit: "Số tiền cọc yêu cầu để giữ chỗ (đơn vị %).",
    lblMinAdvance: "Đặt trước tối thiểu",
    descMinAdvance: "Số giờ tối thiểu khách cần đặt trước.",
    lblMaxAdvance: "Đặt trước tối đa",
    descMaxAdvance: "Số ngày tối đa cho phép khách đặt trước.",
    lblMaxParty: "Số khách tối đa",
    descMaxParty: "Số khách lớn nhất cho phép trong một lần đặt bàn.",
    btnSaving: "Đang lưu...",
    btnSavePolicy: "Lưu chính sách",
    confirmModalTitle: "Xác nhận thay đổi cấu hình",
    confirmModalDesc: "Bạn sắp thay đổi chính sách đặt bàn áp dụng cho <strong>toàn bộ chuỗi</strong>. Thay đổi này sẽ có hiệu lực ngay lập tức trên tất cả chi nhánh.",
    confirmBtnCancel: "Hủy bỏ",
    confirmBtnSave: "Xác nhận lưu"
  },
  amenities: {
    errLoadAmenities: "Lỗi tải danh sách tiện ích.",
    errRequireName: "Vui lòng nhập tên tiện ích.",
    successUpdate: "Cập nhật thành công.",
    successCreate: "Tạo tiện ích thành công.",
    errSubmit: "Có lỗi xảy ra.",
    confirmDelete: 'Bạn có chắc muốn xóa tiện ích "{name}" không?',
    successDelete: "Đã xóa tiện ích.",
    errDelete: "Lỗi xóa tiện ích.",
    errToggleStatus: "Lỗi cập nhật trạng thái.",
    title: "Quản lý Tiện ích",
    subtitle: "Quản lý các tiện ích dịch vụ cho chi nhánh nhà hàng.",
    btnAddAmenity: "Thêm Tiện Ích",
    loadingData: "Đang tải dữ liệu...",
    tableColName: "Tiện ích",
    tableColIcon: "Biểu tượng",
    tableColStatus: "Trạng thái",
    tableColActions: "Thao tác",
    noDescription: "Không có mô tả",
    statusActive: "Hoạt động",
    statusInactive: "Ẩn",
    emptyList: "Chưa có tiện ích nào.",
    modalTitleUpdate: "Cập nhật tiện ích",
    modalTitleAdd: "Thêm tiện ích mới",
    lblName: "Tên tiện ích",
    placeholderName: "VD: Bãi đỗ xe ô tô",
    lblIcon: "Tên biểu tượng Lucide",
    placeholderIcon: "VD: Car, Wifi, Baby...",
    iconHint: "Tìm tên icon tại lucide.dev/icons",
    lblDesc: "Mô tả",
    placeholderDesc: "Mô tả ngắn gọn...",
    btnCancel: "Hủy",
    btnSave: "Lưu"
  },
  vouchers: {
    statusActive: "Đang phát hành",
    statusInactive: "Bản nháp/Tạm dừng",
    statusExpired: "Đã kết thúc",
    statusScheduled: "Sắp diễn ra",
    errLoadList: "Lỗi tải danh sách",
    successEndEarly: "Đã kết thúc sớm voucher",
    errEndEarly: "Lỗi khi kết thúc sớm",
    successDelete: "Đã xóa voucher",
    errDelete: "Lỗi khi xóa",
    title: "Quản lý Khuyến mãi",
    subtitle: "Tạo và quản lý các mã giảm giá cho nhà hàng",
    btnAdd: "Thêm voucher mới",
    searchPlaceholder: "Tìm mã voucher...",
    filterAllStatus: "Tất cả trạng thái",
    filterActive: "Đang phát hành",
    filterScheduled: "Sắp diễn ra",
    filterExpired: "Đã kết thúc",
    filterInactive: "Bản nháp / Tạm dừng",
    thCode: "MÃ VOUCHER",
    thDiscount: "GIẢM GIÁ",
    thUsage: "LƯỢT DÙNG",
    thTime: "THỜI GIAN ÁP DỤNG",
    thStatus: "TRẠNG THÁI",
    thActions: "THAO TÁC",
    loading: "Đang tải...",
    emptyTitle: "Chưa có voucher nào",
    emptyDesc: "Bạn chưa tạo voucher hoặc không có kết quả tìm kiếm.",
    branchSpecific: "Chi nhánh riêng",
    branchAll: "Toàn chuỗi",
    maxDiscount: "Tối đa: ",
    noLimit: "Không giới hạn",
    fromTime: "",
    toTime: "Đến: ",
    actionEdit: "Chỉnh sửa",
    actionEndEarly: "Kết thúc sớm",
    actionDelete: "Xóa",
    noResults: "Không có kết quả",
    paginationDesc: "Đang hiển thị {from} đến {to} trong tổng số {total} mã",
    modalTitleDelete: "Xóa Khuyến mãi",
    modalTitleEndEarly: "Kết thúc sớm",
    modalDescDelete: 'Bạn có chắc chắn muốn xóa mã giảm giá "{code}"? Hành động này không thể hoàn tác.',
    modalDescEndEarly: 'Bạn có chắc chắn muốn kết thúc sớm mã "{code}"? Người dùng sẽ không thể sử dụng mã này nữa.',
    modalBtnCancel: "Hủy",
    modalBtnDelete: "Xóa",
    modalBtnEndEarly: "Kết thúc",
    form: {
      errCodeReq: "Mã voucher là bắt buộc",
      errCodeFormat: "Mã chỉ chứa chữ in hoa, số, gạch nối",
      errDiscountValue: "Mức giảm giá phải từ 1% đến 100%",
      errStartReq: "Ngày bắt đầu là bắt buộc",
      errEndReq: "Ngày kết thúc là bắt buộc",
      errEndBeforeStart: "Thời gian kết thúc phải sau thời gian bắt đầu",
      errStartPast: "Thời gian bắt đầu không được trong quá khứ",
      errEndPast: "Thời gian kết thúc không được trong quá khứ",
      errGeneric: "Đã xảy ra lỗi",
      titleAdd: "Thêm Voucher Mới",
      titleEdit: "Chỉnh sửa Voucher",
      descAdd: "Điền thông tin dưới đây để tạo mã giảm giá mới",
      descEdit: "Cập nhật thông tin cho mã giảm giá",
      cardBasic: "Thông tin cơ bản",
      cardConditions: "Điều kiện áp dụng",
      cardTime: "Thời gian áp dụng",
      lblCode: "Mã Voucher",
      placeholderCode: "VD: SUMMER2024",
      lblBranch: "Chi nhánh áp dụng",
      valAllBranch: "Tất cả chi nhánh",
      lblDiscount: "Mức giảm giá (%)",
      lblMaxDiscount: "Giảm tối đa (VNĐ)",
      placeholderMaxDiscount: "Không điền = Không giới hạn",
      lblMinOrder: "Đơn tối thiểu (VNĐ)",
      lblUsageLimit: "Giới hạn số lượt dùng",
      placeholderUsageLimit: "Không điền = Không giới hạn",
      lblStart: "Bắt đầu",
      lblEnd: "Kết thúc",
      lblActive: "Kích hoạt voucher",
      descActive: "Cho phép sử dụng voucher này",
      lblStatusActive: "Trạng thái hiện tại: Đang diễn ra",
      descStatusActive: "Không thể đổi thời gian bắt đầu khi voucher đang chạy",
      lblStatusScheduled: "Trạng thái hiện tại: Sắp diễn ra",
      descStatusScheduled: "Có thể đổi ngày bắt đầu (phải trong tương lai)",
      btnCancel: "Hủy bỏ",
      btnSave: "Lưu thay đổi",
      btnCreate: "Tạo Voucher",
      submitting: "Đang lưu..."
    },
    page: {
      addSuccess: "Đã tạo voucher thành công",
      addError: "Đã xảy ra lỗi khi tạo voucher",
      editSuccess: "Đã cập nhật voucher thành công",
      editError: "Đã xảy ra lỗi khi cập nhật voucher",
      loading: "Đang tải...",
      notFound: "Không tìm thấy voucher"
    }
  },
  layout: {
    sidebar: {
      overview: "Tổng quan",
      branches: "Quản lý Chi nhánh",
      myBranch: "Chi nhánh của tôi",
      mapTemplates: "Mẫu Sơ đồ bàn",
      menu: "Thực đơn",
      categories: "Danh mục",
      vouchers: "Khuyến mãi",
      analytics: "Phân tích",
      systemConfig: "Cấu hình hệ thống",
      bookingRules: "Chính sách đặt bàn",
      amenities: "Tiện ích"
    },
    header: {
      searchPlaceholder: "Search menu items, categories...",
      managementPortal: "Management Portal",
      home: "Về Trang Chủ",
      adminPortal: "Vào Trang Quản Trị",
      managerPortal: "Vào Trang Quản Lý",
      profile: "Hồ sơ cá nhân",
      logout: "Đăng xuất",
      defaultUser: "Người dùng"
    }
  }
};
