export const MANAGER_TEXTS = {
  bookings: {
    loading: "Đang tải dữ liệu chi nhánh...",
    title: "Quản lý Đặt bàn & Sơ đồ",
    subtitle: "Theo dõi trạng thái bàn theo thời gian thực (Real-time).",
    refreshBtn: "Làm mới",
    filterDateLabel: "Ngày",
    filterShiftLabel: "Ca phục vụ",
    shiftLunch: "Ca Trưa",
    shiftDinner: "Ca Tối",
    listTitle: "Danh sách đặt bàn ({count})",
    emptyList: "Không có đơn đặt bàn nào trong ca này.",
    guestWalkIn: "Khách vãng lai",
    phoneNa: "N/A",
    timeLabel: "Thời gian",
    timeNa: "N/A",
    guestCountLabel: "Số khách",
    guestCountUnit: "người",
    tablePrefix: "Bàn",
    statusPrefix: "Trạng thái:",
    capacityUnit: "chỗ",
    status: {
      HOLDING: "Giữ chỗ",
      PENDING_PAYMENT: "Chờ thanh toán",
      PENDING_DEPOSIT: "Chờ cọc",
      CONFIRMED: "Đã xác nhận",
      OCCUPIED: "Đang dùng bữa",
      COMPLETED: "Hoàn thành",
      CANCELLED: "Đã hủy",
      NO_SHOW: "Không đến"
    }
  },
  menus: {
    loading: "Đang tải thực đơn...",
    errorFetch: "Lỗi lấy dữ liệu thực đơn",
    errorUpdate: "Lỗi cập nhật",
    errorSaveLocal: "Lỗi lưu món ăn",
    errorDeleteLocal: "Lỗi xóa món ăn",
    confirmDelete: "Bạn có chắc muốn xóa món ăn này?",
    title: "Quản Lý Thực Đơn Chi Nhánh",
    subtitle: "Quản lý số lượng dự kiến của món ăn và thêm các món ăn đặc trưng của chi nhánh.",
    addLocalBtn: "Thêm Món (Local)",
    emptyCategory: "Chưa có món ăn nào trong danh mục này.",
    tagMaster: "Master",
    tagLocal: "Local",
    currency: "đ",
    btnOverride: "Số Lượng & Trạng Thái",
    statusAvailable: "Đang phục vụ",
    statusUnavailable: "Hết hàng / Tắt",
    stockPrefix: "Số lượng dự kiến:",
    
    overrideModal: {
      titlePrefix: "Cập nhật:",
      subtitle: "Các thay đổi này chỉ áp dụng tại chi nhánh của bạn.",
      enableSelling: "Bật bán món này",
      stockLabel: "Số lượng dự kiến",
      cancelBtn: "Hủy",
      saveBtn: "Lưu thay đổi"
    },
    
    editLocalModal: {
      title: "Sửa món Local",
      nameLabel: "Tên món",
      descLabel: "Mô tả (Tùy chọn)",
      priceLabel: "Giá cơ bản (VNĐ)",
      stockLabel: "Tồn kho",
      linkLabel: "Link Ảnh (Tùy chọn)",
      linkPlaceholder: "https://example.com/image.jpg",
      enableSelling: "Cho phép bán ngay",
      cancelBtn: "Hủy",
      saveBtn: "Lưu thay đổi"
    },
    addLocalItem: {
      errorFetch: "Lỗi lấy danh mục",
      errorNegativeStock: "Số lượng tồn kho không được âm.",
      errorNoCategory: "Vui lòng chọn danh mục.",
      errorCreateItem: "Lỗi tạo món ăn",
      errorUpload: "Lỗi upload ảnh",
      successAlert: "Thêm món ăn hoàn tất!",
      skipUploadAlert: "Bỏ qua tải ảnh, quay về danh sách.",
      step1Title: "Bước 1: Thông tin cơ bản",
      step2Title: "Bước 2: Hình ảnh món ăn",
      nameLabel: "Tên món",
      categoryLabel: "Danh mục",
      categoryPlaceholder: "-- Chọn danh mục --",
      descLabel: "Mô tả món ăn",
      priceLabel: "Giá bán (VNĐ)",
      stockLabel: "Tồn kho",
      showAfterCreate: "Hiển thị món ăn ngay sau khi tạo",
      cancelBtn: "Hủy",
      nextBtn: "Tiếp theo",
      savedInfoPrefix: "Đã lưu thông tin món:",
      uploadTitle: "Upload ảnh minh họa",
      uploadDesc: "JPG, PNG hoặc WebP. Tối đa 5MB.",
      chooseFileBtn: "Chọn file từ máy tính",
      selectedPrefix: "Đã chọn:",
      skipBtn: "Bỏ qua",
      uploadingBtn: "Đang tải lên...",
      finishBtn: "Hoàn thành tải ảnh"
    }
  }
};
