import { Branch } from './branch-management.types';

export const MOCK_BRANCHES: Branch[] = [
  {
    _id: 'BR-1042',
    name: 'Downtown Metro',
    address: '123 Nguyen Hue, District 1, HCMC',
    hotline: '028-1234-5678',
    open_time: '09:00',
    close_time: '22:00',
    status: 'OPEN',
    overload_threshold: 90,
    manager_name: 'Sarah Jenkins',
    manager_avatar: 'https://i.pravatar.cc/150?u=sarah',
    current_capacity_percent: 45,
  },
  {
    _id: 'BR-1045',
    name: 'Midtown Express',
    address: '456 Le Loi, District 1, HCMC',
    hotline: '028-8765-4321',
    open_time: '10:00',
    close_time: '23:00',
    status: 'FULL',
    overload_threshold: 85,
    manager_name: 'Marcus Reed',
    manager_avatar: '',
    current_capacity_percent: 92,
  },
  {
    _id: 'BR-1088',
    name: 'Westside Plaza',
    address: '789 Vo Van Tan, District 3, HCMC',
    hotline: '028-1111-2222',
    open_time: '00:00',
    close_time: '00:00',
    status: 'SETUP',
    overload_threshold: 80,
    current_capacity_percent: 0,
  },
  {
    _id: 'BR-1089',
    name: 'District 2 Hub',
    address: '12 Thao Dien, District 2, HCMC',
    hotline: '028-2222-3333',
    open_time: '08:00',
    close_time: '21:00',
    status: 'OPEN',
    overload_threshold: 85,
    manager_name: 'David Tran',
    current_capacity_percent: 60,
  },
  {
    _id: 'BR-1090',
    name: 'Phu My Hung Center',
    address: '45 Nguyen Van Linh, District 7, HCMC',
    hotline: '028-3333-4444',
    open_time: '07:00',
    close_time: '22:00',
    status: 'OPEN',
    overload_threshold: 95,
    manager_name: 'Linda Le',
    current_capacity_percent: 80,
  },
  {
    _id: 'BR-1091',
    name: 'Tan Binh Square',
    address: '89 Cong Hoa, Tan Binh, HCMC',
    hotline: '028-4444-5555',
    open_time: '09:00',
    close_time: '23:00',
    status: 'FULL',
    overload_threshold: 80,
    manager_name: 'Kevin Nguyen',
    current_capacity_percent: 85,
  },
  {
    _id: 'BR-1092',
    name: 'Go Vap Station',
    address: '120 Quang Trung, Go Vap, HCMC',
    hotline: '028-5555-6666',
    open_time: '06:00',
    close_time: '20:00',
    status: 'OPEN',
    overload_threshold: 90,
    manager_name: 'Mai Phan',
    current_capacity_percent: 30,
  },
  {
    _id: 'BR-1093',
    name: 'Binh Thanh Riverside',
    address: '34 Dien Bien Phu, Binh Thanh, HCMC',
    hotline: '028-6666-7777',
    open_time: '00:00',
    close_time: '00:00',
    status: 'SETUP',
    overload_threshold: 85,
    current_capacity_percent: 0,
  },
  {
    _id: 'BR-1094',
    name: 'Thu Duc Campus',
    address: '56 Vo Van Ngan, Thu Duc, HCMC',
    hotline: '028-7777-8888',
    open_time: '07:00',
    close_time: '21:00',
    status: 'OPEN',
    overload_threshold: 80,
    manager_name: 'John Smith',
    current_capacity_percent: 75,
  },
  {
    _id: 'BR-1095',
    name: 'District 5 Chinatown',
    address: '78 Tran Hung Dao, District 5, HCMC',
    hotline: '028-8888-9999',
    open_time: '08:00',
    close_time: '22:00',
    status: 'OPEN',
    overload_threshold: 90,
    manager_name: 'Hoa Ly',
    current_capacity_percent: 50,
  },
  {
    _id: 'BR-1096',
    name: 'District 10 Center',
    address: '90 3/2 Street, District 10, HCMC',
    hotline: '028-9999-0000',
    open_time: '09:00',
    close_time: '22:30',
    status: 'FULL',
    overload_threshold: 85,
    manager_name: 'Binh Truong',
    current_capacity_percent: 90,
  },
  {
    _id: 'BR-1097',
    name: 'Phu Nhuan Hub',
    address: '112 Phan Dang Luu, Phu Nhuan, HCMC',
    hotline: '028-0000-1111',
    open_time: '06:30',
    close_time: '21:30',
    status: 'OPEN',
    overload_threshold: 90,
    manager_name: 'An Vu',
    current_capacity_percent: 20,
  }
];
